name: App_Ventas_ExportPdf
description: Un nuevo proyecto de Flutter.

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.2.0
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.19.0
  url_launcher: ^6.2.4
